"""initial schema

Revision ID: 642308362449
Revises: 
Create Date: 2026-06-04 14:00:55.203246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642308362449'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_address', sa.Text(), nullable=False),
    sa.Column('business_phone', sa.String(length=20), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('next_invoice_number', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
    sa.Column('smtp_from_name', sa.String(length=200), nullable=True),
    sa.Column('plan_slot_reminder_days', sa.Integer(), nullable=False),
    sa.Column('appointment_reminder_48h', sa.Boolean(), nullable=False),
    sa.Column('max_home_visits_per_day', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_address', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_date', 'invoices', ['date'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_customer_id', 'payments', ['customer_id'], unique=False)
    op.create_index('ix_payments_date', 'payments', ['date'], unique=False)
    op.create_index('ix_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_subscription_id', 'payments', ['subscription_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('specialisms', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_practitioners_email', 'practitioners', ['email'], unique=False)
    op.create_index('ix_practitioners_is_active', 'practitioners', ['is_active'], unique=False)
    op.create_index('ix_practitioners_role', 'practitioners', ['role'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_level', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_stock_level', 'products', ['stock_level'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('preferred_contact', sa.String(length=20), nullable=False),
    sa.Column('health_flags', sa.JSON(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_is_active', 'customers', ['is_active'], unique=False)
    op.create_index('ix_customers_practitioner_id', 'customers', ['practitioner_id'], unique=False)
    op.create_table('practitioner_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practitioner_availability_unique', 'practitioner_availability', ['practitioner_id', 'day_of_week'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('practitioner_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_practitioner_id', 'users', ['practitioner_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('plan_slot_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_plan_generated', sa.Boolean(), nullable=False),
    sa.Column('parent_appointment_id', sa.String(length=36), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_mins > 0', name='ck_appointments_duration'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_customer_id', 'appointments', ['customer_id'], unique=False)
    op.create_index('ix_appointments_plan_slot_id', 'appointments', ['plan_slot_id'], unique=True)
    op.create_index('ix_appointments_practitioner_id', 'appointments', ['practitioner_id'], unique=False)
    op.create_index('ix_appointments_scheduled_at', 'appointments', ['scheduled_at'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=True),
    sa.Column('sent_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_communication_logs_channel', 'communication_logs', ['channel'], unique=False)
    op.create_index('ix_communication_logs_customer_id', 'communication_logs', ['customer_id'], unique=False)
    op.create_index('ix_communication_logs_sent_at', 'communication_logs', ['sent_at'], unique=False)
    op.create_index('ix_communication_logs_status', 'communication_logs', ['status'], unique=False)
    op.create_table('customer_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_assignments_practitioner_id', 'customer_assignments', ['practitioner_id'], unique=False)
    op.create_index('ix_customer_assignments_unique', 'customer_assignments', ['customer_id', 'practitioner_id'], unique=True)
    op.create_table('customer_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_notes_created_at', 'customer_notes', ['created_at'], unique=False)
    op.create_index('ix_customer_notes_customer_id', 'customer_notes', ['customer_id'], unique=False)
    op.create_index('ix_customer_notes_is_synced', 'customer_notes', ['is_synced'], unique=False)
    op.create_index('ix_customer_notes_practitioner_id', 'customer_notes', ['practitioner_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contract_length', sa.String(length=50), nullable=False),
    sa.Column('cancellation_terms', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_is_active', 'plans', ['is_active'], unique=False)
    op.create_index('ix_plans_is_template', 'plans', ['is_template'], unique=False)
    op.create_table('practitioner_absences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practitioner_id', sa.String(length=36), nullable=False),
    sa.Column('absence_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_absences_end_date'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practitioner_absences_dates', 'practitioner_absences', ['practitioner_id', 'start_date', 'end_date'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('date_taken', sa.Date(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('practitioner_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_results_customer_id', 'test_results', ['customer_id'], unique=False)
    op.create_index('ix_test_results_date_taken', 'test_results', ['date_taken'], unique=False)
    op.create_index('ix_test_results_status', 'test_results', ['status'], unique=False)
    op.create_index('ix_test_results_test_type', 'test_results', ['test_type'], unique=False)
    op.create_table('appointment_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_reminders_appointment_id', 'appointment_reminders', ['appointment_id'], unique=False)
    op.create_index('ix_appointment_reminders_scheduled_for', 'appointment_reminders', ['scheduled_for'], unique=False)
    op.create_index('ix_appointment_reminders_status', 'appointment_reminders', ['status'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_per_cycle', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_items_plan_id', 'plan_items', ['plan_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=False),
    sa.Column('months_billed', sa.Integer(), nullable=False),
    sa.Column('paused_at', sa.Date(), nullable=True),
    sa.Column('pause_resume_date', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.Date(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_prorata_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_billed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_cycle_start', sa.Date(), nullable=False),
    sa.Column('current_cycle_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('billing_day >= 1 AND billing_day <= 31', name='ck_subscriptions_billing_day'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_customer_id', 'subscriptions', ['customer_id'], unique=False)
    op.create_index('ix_subscriptions_next_billing_date', 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('test_markers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_result_id', sa.String(length=36), nullable=False),
    sa.Column('marker_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('reference_high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_out_of_range', sa.Boolean(), nullable=False),
    sa.Column('flag', sa.String(length=20), nullable=False),
    sa.Column('practitioner_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_markers_marker_name', 'test_markers', ['marker_name'], unique=False)
    op.create_index('ix_test_markers_test_result_id', 'test_markers', ['test_result_id'], unique=False)
    op.create_table('plan_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('suggested_date', sa.Date(), nullable=False),
    sa.Column('booking_window_start', sa.Date(), nullable=False),
    sa.Column('booking_window_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('missed_reason', sa.Text(), nullable=True),
    sa.Column('missed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_plan_slots_appointment_id', use_alter=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_index('ix_plan_slots_booking_window_start', 'plan_slots', ['booking_window_start'], unique=False)
    op.create_index('ix_plan_slots_status', 'plan_slots', ['status'], unique=False)
    op.create_index('ix_plan_slots_subscription_id', 'plan_slots', ['subscription_id'], unique=False)
    op.create_index('ix_plan_slots_suggested_date', 'plan_slots', ['suggested_date'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('plan_slot_id', sa.String(length=36), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_slot_id'], ['plan_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_plan_slot_id', 'orders', ['plan_slot_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('product_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_transactions_created_at', 'product_transactions', ['created_at'], unique=False)
    op.create_index('ix_product_transactions_order_id', 'product_transactions', ['order_id'], unique=False)
    op.create_index('ix_product_transactions_product_id', 'product_transactions', ['product_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('test_marker_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('linked_order_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_marker_id'], ['test_markers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_customer_id', 'recommendations', ['customer_id'], unique=False)
    op.create_index('ix_recommendations_status', 'recommendations', ['status'], unique=False)
    op.create_index('ix_recommendations_test_marker_id', 'recommendations', ['test_marker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_test_marker_id', table_name='recommendations')
    op.drop_index('ix_recommendations_status', table_name='recommendations')
    op.drop_index('ix_recommendations_customer_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_product_transactions_product_id', table_name='product_transactions')
    op.drop_index('ix_product_transactions_order_id', table_name='product_transactions')
    op.drop_index('ix_product_transactions_created_at', table_name='product_transactions')
    op.drop_table('product_transactions')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_plan_slot_id', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_plan_slots_suggested_date', table_name='plan_slots')
    op.drop_index('ix_plan_slots_subscription_id', table_name='plan_slots')
    op.drop_index('ix_plan_slots_status', table_name='plan_slots')
    op.drop_index('ix_plan_slots_booking_window_start', table_name='plan_slots')
    op.drop_table('plan_slots')
    op.drop_index('ix_test_markers_test_result_id', table_name='test_markers')
    op.drop_index('ix_test_markers_marker_name', table_name='test_markers')
    op.drop_table('test_markers')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_next_billing_date', table_name='subscriptions')
    op.drop_index('ix_subscriptions_customer_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_plan_items_plan_id', table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index('ix_appointment_reminders_status', table_name='appointment_reminders')
    op.drop_index('ix_appointment_reminders_scheduled_for', table_name='appointment_reminders')
    op.drop_index('ix_appointment_reminders_appointment_id', table_name='appointment_reminders')
    op.drop_table('appointment_reminders')
    op.drop_index('ix_test_results_test_type', table_name='test_results')
    op.drop_index('ix_test_results_status', table_name='test_results')
    op.drop_index('ix_test_results_date_taken', table_name='test_results')
    op.drop_index('ix_test_results_customer_id', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('ix_practitioner_absences_dates', table_name='practitioner_absences')
    op.drop_table('practitioner_absences')
    op.drop_index('ix_plans_is_template', table_name='plans')
    op.drop_index('ix_plans_is_active', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_customer_notes_practitioner_id', table_name='customer_notes')
    op.drop_index('ix_customer_notes_is_synced', table_name='customer_notes')
    op.drop_index('ix_customer_notes_customer_id', table_name='customer_notes')
    op.drop_index('ix_customer_notes_created_at', table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index('ix_customer_assignments_unique', table_name='customer_assignments')
    op.drop_index('ix_customer_assignments_practitioner_id', table_name='customer_assignments')
    op.drop_table('customer_assignments')
    op.drop_index('ix_communication_logs_status', table_name='communication_logs')
    op.drop_index('ix_communication_logs_sent_at', table_name='communication_logs')
    op.drop_index('ix_communication_logs_customer_id', table_name='communication_logs')
    op.drop_index('ix_communication_logs_channel', table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_scheduled_at', table_name='appointments')
    op.drop_index('ix_appointments_practitioner_id', table_name='appointments')
    op.drop_index('ix_appointments_plan_slot_id', table_name='appointments')
    op.drop_index('ix_appointments_customer_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_practitioner_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_practitioner_availability_unique', table_name='practitioner_availability')
    op.drop_table('practitioner_availability')
    op.drop_index('ix_customers_practitioner_id', table_name='customers')
    op.drop_index('ix_customers_is_active', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_table('customers')
    op.drop_table('rooms')
    op.drop_index('ix_products_stock_level', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_practitioners_role', table_name='practitioners')
    op.drop_index('ix_practitioners_is_active', table_name='practitioners')
    op.drop_index('ix_practitioners_email', table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index('ix_payments_subscription_id', table_name='payments')
    op.drop_index('ix_payments_invoice_id', table_name='payments')
    op.drop_index('ix_payments_date', table_name='payments')
    op.drop_index('ix_payments_customer_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_date', table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
